name = "cuhksz-ling-cafe-glass"
main = "worker.js"
compatibility_date = "2026-09-07"
workers_dev = true
preview_urls = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true

[[durable_objects.bindings]]
name = "MENU_STORE"
class_name = "MenuStore"

[exports.MenuStore]
type = "durable-object"
storage = "sqlite"

[vars]
ADMIN_USERNAME = "Trent"
ADMIN_PASSWORD_HASH = "6d19ca72de1fe7973e5a763cdbaf47af34674d4f45a8a2cacd881b751d680a4f"
